type: thenomad-site
version: 0.0.1

components:
  blogSite:
    type: static-website
    inputs:
      name: thenomad-site
      contentPath: ${self.path}/site
      templateValues: {}
      contentIndex: index.html
      contentError: error.html
      hostingRegion: us-east-1
      hostingDomain: thenomad.xyz
      aliasDomain: thenomad.xyz